server:
  port: 8062
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root


spring:
  datasource:
    # 数据库名
    name: bt_order
    url: jdbc:mysql://47.92.111.224:3306/${spring.datasource.name}?serverTimezone=GMT%2B8
    username: root
    password: rsbfgkjlgvedfjkvg
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
# 打印sql
logging:
  level:
    com.gexiao.demo.dao : debug
# 网关参数
gateway:
  # 不校验的uri
  unchecked:
    - /user/login
    - /user/add
    - /user/logout


