server:
  port: 8062
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml